### ISSUE TITLE
Automatically detect provider

### ISSUE THREAD

**Issue by oskarrough** [internet4000/media-now#3]
For kicks, I'd like to be able to do

```
/provider/YyI52_FEYgY
/provider/121814744
```

and it will tell you which provider it is. Now, it could be tricky to guess but both Vimeo and YouTube follow strict id conventions which some regex should be able to find.

**Comment by hellerve** [comment]
Vimeo has [a clear convention](https://vimeo.com/forums/topic:267078), but for Youtube it is conincidental and [in no way guaranteed](http://webapps.stackexchange.com/a/54448). If you _do_ want to rely on the format, however, I suggest using these regexes:
```javascript
let ytrx = /^[-_A-Za-z0-9]{10}[AEIMQUYcgkosw048]$/;
let vmrx = /^[0-9]{5}[0-9]*$/;
// i have no idea how long these are by definition, this assumes at least 5
```

I hope that helps.

Cheers

**Comment by oskarrough** [comment]
Thanks!

I found this module which seems to do the trick https://github.com/Zod-/jsVideoUrlParser

**Comment by hellerve** [comment]
It looks a bit heavy to me for what you're trying to achieve, but you can try to give that a go, sure :)

**Comment by oskarrough** [comment]
Closing. Will implement if we need it one day.
